/* Inserts para la tabla SEG_PERFIL */

INSERT INTO SEG_PERFIL (COD_PERFIL, NOMBRE, VERSION) VALUES ('PERF001', 'Andres', 1);
INSERT INTO SEG_PERFIL (COD_PERFIL, NOMBRE, VERSION) VALUES ('PERF002', 'Alex', 1);
INSERT INTO SEG_PERFIL (COD_PERFIL, NOMBRE, VERSION) VALUES ('PERF003', 'Mariano', 1);

/* Inserts para la tabla SEG_USUARIO */

INSERT INTO SEG_USUARIO (COD_USUARIO, MAIL, CLAVE, NOMBRE, INTENTOS_FALLIDOS, SUELDO, FECHA_NACIMIENTO, VERSION) VALUES (1, 'usuario1@mail.com', 'clave1', 'Usuario 1', NULL, 1000.00, '2022-01-01', 1);
INSERT INTO SEG_USUARIO (COD_USUARIO, MAIL, CLAVE, NOMBRE, INTENTOS_FALLIDOS, SUELDO, FECHA_NACIMIENTO, VERSION) VALUES (2, 'usuario2@mail.com', 'clave2', 'Usuario 2', NULL, 2000.00, '2022-02-02', 1);
INSERT INTO SEG_USUARIO (COD_USUARIO, MAIL, CLAVE, NOMBRE, INTENTOS_FALLIDOS, SUELDO, FECHA_NACIMIENTO, VERSION) VALUES (3, 'usuario3@mail.com', 'clave3', 'Usuario 3', NULL, 3000.00, '2022-03-03', 1);

/* Inserts para la tabla SEG_USUARIO_PERFIL */

INSERT INTO SEG_USUARIO_PERFIL (COD_USUARIO, COD_PERFIL, FECHA_CREACION, ES_ACTIVO, VERSION) VALUES (1, 'PERF001', CURRENT_TIMESTAMP, true, 1);
INSERT INTO SEG_USUARIO_PERFIL (COD_USUARIO, COD_PERFIL, FECHA_CREACION, ES_ACTIVO, VERSION) VALUES (2, 'PERF001', CURRENT_TIMESTAMP, true, 1);
INSERT INTO SEG_USUARIO_PERFIL (COD_USUARIO, COD_PERFIL, FECHA_CREACION, ES_ACTIVO, VERSION) VALUES (2, 'PERF002', CURRENT_TIMESTAMP, true, 1);
INSERT INTO SEG_USUARIO_PERFIL (COD_USUARIO, COD_PERFIL, FECHA_CREACION, ES_ACTIVO, VERSION) VALUES (3, 'PERF003', CURRENT_TIMESTAMP, true, 1);
